name = "linyuan-bot"
main = "src/worker.js"
compatibility_date = "2026-01-04"

[[d1_databases]]
binding = "DB"
database_name = "linyuanpic-bot"
database_id = "9359a3db-d914-4ec6-aba3-f74842e13a42"

[[kv_namespaces]]
binding = "KV"
id = "8c0ca324d0384ec4ae826f95e76f46d3"

[triggers]
crons = ["*/5 * * * *"]

[vars]
ADMIN_USER_IDS = "7204268059"
TZ = "Asia/Shanghai"
BOT_TOKEN = "8366967396:AAEvVWxP6PVJfAqNXm-Lh2xfZzTzniUYxGA"

# You will set secrets via: wrangler secret put BOT_TOKEN
